# Generated by Django 5.2.1 on 2025-05-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('superadmin', 'Super Admin')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user_tbl',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='user_tbl_usernam_0f2b80_idx'), models.Index(fields=['role', 'is_active'], name='user_tbl_role_fb01e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('worked_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completion_report', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'task_tbl',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to'], name='task_tbl_assigne_c5f8ef_idx'), models.Index(fields=['status'], name='task_tbl_status_3a665f_idx'), models.Index(fields=['due_date', 'status'], name='task_tbl_due_dat_e83b62_idx')],
            },
        ),
    ]
